name: deploy-to-gh-pages
on:
  push:
    branches:
      - main
env:
  DOMAIN_NAME: hessforlanco.org
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      COMMIT_USER_NAME: GitHub Action Runner
      COMMIT_USER_EMAIL: support+actions@github.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Set Git configs
        run: |
          git config user.name "${{ env.COMMIT_USER_NAME }}"
          git config user.email "${{ env.COMMIT_USER_EMAIL }}"
          git remote set-url origin "https://git:${{ github.token }}@github.com/${{ github.repository }}.git"

      - name: Export and deploy
        env:
          BUILD_DIR: build
        run: |
          npm run export -- -o ${{ env.BUILD_DIR }}
          touch ${{ env.BUILD_DIR }}/.nojekyll
          echo "${{ env.DOMAIN_NAME }}" > ${{ env.BUILD_DIR }}/CNAME
          npm run deploy -- -d ${{ env.BUILD_DIR }} --dotfiles --user "${{ env.COMMIT_USER_NAME }} <${{ env.COMMIT_USER_EMAIL }}>"
