name: deploy-to-gh-pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Set Git configs
        run: |
          git config user.name "GitHub Action Runner"
          git config user.email "support+actions@github.com"
          git remote set-url origin https://git:${{ github.token }}@github.com/${{ github.repository }}.git

      - name: Export and deploy
        run: |
          npm run export -- -o build
          touch build/.nojekyll
          echo "hessforlanco.org" > build/CNAME
          npm run deploy -- -d build --dotfiles --user "GitHub Action Runner <support+actions@github.com>"
